highlighter: rouge
safe: false
lsi: false
production_url: http://www.robersonlab.org
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Gemfile", "Gemfile.lock"]
gems:
  - jekyll-sitemap
